name = "Gensou"
author = "Maboroshi Kobo"
version = "1.0.0-SNAPSHOT"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "131690447c330ee556c2a8715abef7f092f7e4c4b4a5ad039186470c1f8c6a0f"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
