name = "Gensou"
author = "Maboroshi Kobo"
version = "1.0.0-SNAPSHOT"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c138910ac10f20656f1433b4648236ef1a5100a1d3053c561a5767cb6cd9f4c4"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
